[project]
name = "nber"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.109.1",
    "pandas>=2.3.3",
    "python-dotenv>=1.1.1",
    "streamlit>=1.50.0",
    "youtube-transcript-api>=1.2.2",
    "yt-dlp>=2025.9.26",
]
